# Generated by Django 5.2 on 2025-05-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('playlist_name', models.CharField()),
                ('playlist_id', models.CharField(null=True)),
                ('name', models.CharField()),
                ('converted', models.BooleanField(default=False)),
            ],
        ),
    ]
